//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 01:25:43 PM CET 
//

package eu.europa.ec.fisheries.uvms.reporting.model.schemas;

import javax.xml.bind.annotation.*;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://europa.eu/ec/fisheries/uvms/reporting/model/schemas}ReportingModuleRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="now" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="scopeName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "now",
    "id",
    "userName",
    "scopeName"
})
@XmlRootElement(name = "ReportGetStartAndEndDateRQ")
public class ReportGetStartAndEndDateRQ
    extends ReportingModuleRequest
{

    @XmlElement(required = true)
    protected String now;
    protected long id;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected String scopeName;

    /**
     * Default no-arg constructor
     * 
     */
    public ReportGetStartAndEndDateRQ() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public ReportGetStartAndEndDateRQ(final ReportingModuleMethod method, final String now, final long id, final String userName, final String scopeName) {
        super(method);
        this.now = now;
        this.id = id;
        this.userName = userName;
        this.scopeName = scopeName;
    }

    /**
     * Gets the value of the now property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNow() {
        return now;
    }

    /**
     * Sets the value of the now property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNow(String value) {
        this.now = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the scopeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScopeName() {
        return scopeName;
    }

    /**
     * Sets the value of the scopeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScopeName(String value) {
        this.scopeName = value;
    }

}
