//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 01:25:43 PM CET 
//

package eu.europa.ec.fisheries.uvms.reporting.model.schemas;

import javax.xml.bind.annotation.*;

/**
 * <p>Java class for ReportingModuleRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportingModuleRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="method" type="{http://europa.eu/ec/fisheries/uvms/reporting/model/schemas}ReportingModuleMethod"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportingModuleRequest", propOrder = {
    "method"
})
@XmlSeeAlso({
    ReportGetStartAndEndDateRQ.class
})
public abstract class ReportingModuleRequest {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ReportingModuleMethod method;

    /**
     * Default no-arg constructor
     * 
     */
    public ReportingModuleRequest() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public ReportingModuleRequest(final ReportingModuleMethod method) {
        this.method = method;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingModuleMethod }
     *     
     */
    public ReportingModuleMethod getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingModuleMethod }
     *     
     */
    public void setMethod(ReportingModuleMethod value) {
        this.method = value;
    }

}
