package eu.europa.ec.fisheries.uvms.reporting.model;

public interface ReportFeature {

	String LIST_REPORTS = "LIST_REPORTS";
	String MODIFY_PRIVATE_REPORT = "MODIFY_PRIVATE_REPORT";
    String SHARE_REPORTS_SCOPE = "SHARE_REPORTS_SCOPE";
    String SHARE_REPORTS_GLOBAL = "SHARE_REPORTS_GLOBAL";
    String CREATE_REPORTS = "CREATE_REPORTS";
    String VIEW_REPORT = "VIEW_REPORT";
    String EXECUTE_REPORT = "EXECUTE_REPORT";
    String MODIFY_SCOPE_REPORT = "MODIFY_SCOPE_REPORT";
    String MODIFY_GLOBAL_REPORT = "MODIFY_GLOBAL_REPORT";
    String DELETE_SCOPE_REPORT = "DELETE_SCOPE_REPORTS";
    String DELETE_GLOBAL_REPORT = "DELETE_GLOBAL_REPORTS";
	String DELETE_REPORT = "DELETE_REPORT";
}
