package eu.europa.ec.fisheries.uvms.reporting.service.entities;

// Generated Aug 6, 2015 11:44:29 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Where;

import eu.europa.ec.fisheries.uvms.reporting.service.entities.converter.CharBooleanConverter;

/**
 * ReportEntity generated by hbm2java
 */
@Entity
@Table(name = "report", schema = "reporting")
@Where(clause = "is_deleted <> 'Y'")
public class ReportEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7784224707011748170L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private long id;
	
	@Column(name = "name", nullable = false)
	private String name;
	
	@Column(name = "description")
	private String description;
	
	@Column(name = "filter_expression", nullable = false)
	private String filterExpression;
	
	@Column(name = "out_components", nullable = false)
	private String outComponents;
	
	@Column(name = "scope_id", nullable = false)
	private long scopeId;
	
	@Column(name = "created_by", nullable = false)
	private String createdBy;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 29)
	private Date createdOn;
	
	@Convert(converter=CharBooleanConverter.class)
	@Column(name = "is_shared", nullable = false, length=1)
	private Boolean isShared = false;
	
	@Convert(converter=CharBooleanConverter.class)
	@Column(name = "is_deleted", nullable = true, length=1)
	private Boolean isDeleted = false;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_on", length = 29)
	private Date deletedOn;
	
	@Column(name = "deleted_by")
	private String deletedBy;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "report", orphanRemoval=true, cascade = javax.persistence.CascadeType.ALL)
	private Set<ReportExecutionLogEntity> reportExecutionLogs = new HashSet<ReportExecutionLogEntity>(
			0);

	public ReportEntity() {
	}

	public ReportEntity(long id, String name, String filterExpression,
			String outComponents, long scopeId,
			String createdBy, Date createdOn, Boolean isShared,
			Boolean isDeleted) {
		this.id = id;
		this.name = name;
		this.filterExpression = filterExpression;
		this.outComponents = outComponents;
		this.scopeId = scopeId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.isShared = isShared;
		this.isDeleted = isDeleted;
	}

	public ReportEntity(long id, String name, String description,
			String filterExpression, String outComponents,
			long scopeId, String createdBy, Date createdOn, Boolean isShared,
			Boolean isDeleted, Date deletedOn, String deletedBy,
			Set<ReportExecutionLogEntity> reportExecutionLogs) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.filterExpression = filterExpression;
		this.outComponents = outComponents;
		this.scopeId = scopeId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.isShared = isShared;
		this.isDeleted = isDeleted;
		this.deletedOn = deletedOn;
		this.deletedBy = deletedBy;
		this.reportExecutionLogs = reportExecutionLogs;
	}
	
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	public String getFilterExpression() {
		return this.filterExpression;
	}

	public void setFilterExpression(String filterExpression) {
		this.filterExpression = filterExpression;
	}

	public String getOutComponents() {
		return this.outComponents;
	}

	public void setOutComponents(String outComponents) {
		this.outComponents = outComponents;
	}

	public long getScopeId() {
		return this.scopeId;
	}

	public void setScopeId(long scopeId) {
		this.scopeId = scopeId;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Boolean isIsShared() {
		return this.isShared;
	}
	
	public void setIsShared(Boolean isShared) {
		this.isShared = isShared;
	}

	public Boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	public String getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(String deletedBy) {
		this.deletedBy = deletedBy;
	}

	public Set<ReportExecutionLogEntity> getReportExecutionLogs() {
		return this.reportExecutionLogs;
	}

	public void setReportExecutionLogs(
			Set<ReportExecutionLogEntity> reportExecutionLogs) {
		this.reportExecutionLogs = reportExecutionLogs;
	}

}
