package eu.europa.ec.fisheries.uvms.reporting.service.entities;

// Generated Aug 6, 2015 11:44:29 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ReportExecutionLogEntity generated by hbm2java
 */
@Entity
@Table(name = "report_execution_log", uniqueConstraints = @UniqueConstraint(columnNames = "report_id"), schema = "reporting")
public class ReportExecutionLogEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private long id;
	
	@ManyToOne(targetEntity = ReportEntity.class)
	@JoinColumn(name = "report_id", unique = true, nullable = false)
	private ReportEntity report;
	
	@Column(name = "executed_by", nullable = false)
	private String executedBy;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "executed_on", nullable = false, length = 29)
	private Date executedOn;

	public ReportExecutionLogEntity() {
	}

	public ReportExecutionLogEntity(long id, ReportEntity report, String executedBy,
			Date executedOn) {
		this.id = id;
		this.report = report;
		this.executedBy = executedBy;
		this.executedOn = executedOn;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}


	public ReportEntity getReport() {
		return this.report;
	}

	public void setReport(ReportEntity report) {
		this.report = report;
	}

	public String getExecutedBy() {
		return this.executedBy;
	}

	public void setExecutedBy(String executedBy) {
		this.executedBy = executedBy;
	}

	public Date getExecutedOn() {
		return this.executedOn;
	}

	public void setExecutedOn(Date executedOn) {
		this.executedOn = executedOn;
	}

}
