package eu.europa.ec.fisheries.uvms.reporting.service.entities;

// Generated Aug 6, 2015 11:44:29 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "report")
public class Report implements java.io.Serializable {

	private long id;
	private String name;
	private String description;
	private String filterExpression;
	private String outComponents;
	private boolean isActive;
	private long scopeId;
	private String createdBy;
	private Date createdOn;
	private boolean isShared;
	private boolean isDeleted;
	private Date deletedOn;
	private String deletedBy;
	private Set<ReportExecutionLog> reportExecutionLogs = new HashSet<ReportExecutionLog>(
			0);

	public Report() {
	}

	public Report(long id, String name, String filterExpression,
			String outComponents, boolean isActive, long scopeId,
			String createdBy, Date createdOn, boolean isShared,
			boolean isDeleted) {
		this.id = id;
		this.name = name;
		this.filterExpression = filterExpression;
		this.outComponents = outComponents;
		this.isActive = isActive;
		this.scopeId = scopeId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.isShared = isShared;
		this.isDeleted = isDeleted;
	}

	public Report(long id, String name, String description,
			String filterExpression, String outComponents, boolean isActive,
			long scopeId, String createdBy, Date createdOn, boolean isShared,
			boolean isDeleted, Date deletedOn, String deletedBy,
			Set<ReportExecutionLog> reportExecutionLogs) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.filterExpression = filterExpression;
		this.outComponents = outComponents;
		this.isActive = isActive;
		this.scopeId = scopeId;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.isShared = isShared;
		this.isDeleted = isDeleted;
		this.deletedOn = deletedOn;
		this.deletedBy = deletedBy;
		this.reportExecutionLogs = reportExecutionLogs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "filter_expression", nullable = false)
	public String getFilterExpression() {
		return this.filterExpression;
	}

	public void setFilterExpression(String filterExpression) {
		this.filterExpression = filterExpression;
	}

	@Column(name = "out_components", nullable = false)
	public String getOutComponents() {
		return this.outComponents;
	}

	public void setOutComponents(String outComponents) {
		this.outComponents = outComponents;
	}

	@Column(name = "is_active", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "scope_id", nullable = false)
	public long getScopeId() {
		return this.scopeId;
	}

	public void setScopeId(long scopeId) {
		this.scopeId = scopeId;
	}

	@Column(name = "created_by", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 29)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "is_shared", nullable = false)
	public boolean isIsShared() {
		return this.isShared;
	}

	public void setIsShared(boolean isShared) {
		this.isShared = isShared;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_on", length = 29)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@Column(name = "deleted_by")
	public String getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(String deletedBy) {
		this.deletedBy = deletedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "report")
	public Set<ReportExecutionLog> getReportExecutionLogs() {
		return this.reportExecutionLogs;
	}

	public void setReportExecutionLogs(
			Set<ReportExecutionLog> reportExecutionLogs) {
		this.reportExecutionLogs = reportExecutionLogs;
	}

}
