//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 01:25:43 PM CET
//

package eu.europa.ec.fisheries.uvms.reporting.message.model;

public class ObjectFactory {

    public ObjectFactory() {
    }

    public ReportGetStartAndEndDateRQ createReportGetStartAndEndDateRQ() {
        return new ReportGetStartAndEndDateRQ();
    }

    public ReportGetStartAndEndDateRS createReportGetStartAndEndDateRS() {
        return new ReportGetStartAndEndDateRS();
    }

    public ReportingFault createReportingFault() {
        return new ReportingFault();
    }
}
