//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 01:25:43 PM CET 
//

package eu.europa.ec.fisheries.uvms.reporting.message.model;

public class ReportGetStartAndEndDateRS {

    protected String startDate;
    protected String endDate;

    public ReportGetStartAndEndDateRS() {
        super();
    }

    public ReportGetStartAndEndDateRS(final String startDate, final String endDate) {
        this.startDate = startDate;
        this.endDate = endDate;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String value) {
        this.startDate = value;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String value) {
        this.endDate = value;
    }

}
