//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 01:25:43 PM CET 
//

package eu.europa.ec.fisheries.uvms.reporting.message.model;

public class ReportingFault {

    private int code;
    private String fault;

    public ReportingFault() {
    }

    public ReportingFault(final int code, final String fault) {
        this.code = code;
        this.fault = fault;
    }

    public int getCode() {
        return code;
    }

    public void setCode(int value) {
        this.code = value;
    }

    public String getFault() {
        return fault;
    }

    public void setFault(String value) {
        this.fault = value;
    }
}
