//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 01:25:43 PM CET 
//

package eu.europa.ec.fisheries.uvms.reporting.message.model;

public class ReportGetStartAndEndDateRQ extends ReportingModuleRequest {

    protected String now;
    protected long id;
    protected String userName;
    protected String scopeName;

    public ReportGetStartAndEndDateRQ() {
        super();
    }

    public ReportGetStartAndEndDateRQ(final ReportingModuleMethod method, final String now, final long id, final String userName, final String scopeName) {
        super(method);
        this.now = now;
        this.id = id;
        this.userName = userName;
        this.scopeName = scopeName;
    }

    public String getNow() {
        return now;
    }

    public void setNow(String value) {
        this.now = value;
    }

    public long getId() {
        return id;
    }

    public void setId(long value) {
        this.id = value;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String value) {
        this.userName = value;
    }

    public String getScopeName() {
        return scopeName;
    }

    public void setScopeName(String value) {
        this.scopeName = value;
    }
}
